-- Live streaming v2: persistent like count, categories, tags, language,
-- mature flag, slow mode, followers-only chat, and VODs.

ALTER TABLE live_streams
  ADD COLUMN IF NOT EXISTS total_likes BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS language TEXT NOT NULL DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS slow_mode_seconds INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS followers_only_chat BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS mature BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS live_streams_category_status_idx
  ON live_streams (category, status)
  WHERE status = 'live';

CREATE INDEX IF NOT EXISTS live_streams_tags_idx
  ON live_streams USING GIN (tags);

-- Race-free like increment. Anyone authenticated (or anon) can call.
CREATE OR REPLACE FUNCTION increment_stream_likes(p_stream_id UUID)
RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_total BIGINT;
BEGIN
  UPDATE live_streams
  SET total_likes = total_likes + 1
  WHERE id = p_stream_id
  RETURNING total_likes INTO new_total;
  RETURN new_total;
END;
$$;

REVOKE ALL ON FUNCTION increment_stream_likes(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION increment_stream_likes(UUID) TO authenticated, anon;

-- VOD table: one row per Mux Asset that was generated by ending a live stream.
CREATE TABLE IF NOT EXISTS live_vods (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stream_id UUID REFERENCES live_streams(id) ON DELETE SET NULL,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT,
  category TEXT,
  mux_asset_id TEXT NOT NULL UNIQUE,
  mux_playback_id TEXT NOT NULL,
  duration_seconds INT,
  view_count BIGINT NOT NULL DEFAULT 0,
  thumbnail_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS live_vods_user_created_idx
  ON live_vods (user_id, created_at DESC);

ALTER TABLE live_vods ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "VODs are viewable by everyone" ON live_vods;
CREATE POLICY "VODs are viewable by everyone"
  ON live_vods FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can delete own VODs" ON live_vods;
CREATE POLICY "Users can delete own VODs"
  ON live_vods FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own VODs" ON live_vods;
CREATE POLICY "Users can update own VODs"
  ON live_vods FOR UPDATE
  USING (auth.uid() = user_id);
